version: "3"

services:
  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      env.env
    restart: always

  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./main:/code
      - ./data/static:/static
      - ./.git/HEAD:/code/.git/HEAD:ro
      - ./.git/refs:/code/.git/refs:ro
    env_file:
      env.env
    expose:
      - 8099
    depends_on:
      - db
    links:
      - "db:db"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/conf:/etc/nginx/conf.d
      - ./data/static:/static
    ports:
      - 8022:8022
    depends_on:
      - web
    restart: always
